# docker-compose.yml
version: '3.3'

services:
  laracom-demo-cli:
    depends_on:
      - jaeger
    build: ./demo-cli
    environment:
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
      MICRO_TRACE_SERVER: "jaeger:6831"

  laracom-demo-service:
    depends_on:
      - etcd1
      - etcd2
      - etcd3
      - jaeger
    build: ./demo-service
    ports:
      - 9091:9091
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
      MICRO_TRACE_SERVER: "jaeger:6831"

  laracom-demo-api:
    build: ./demo-api
    depends_on:
      - laracom-demo-service
    environment:
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
      MICRO_TRACE_SERVER: "jaeger:6831"

  laracom-user-service:
    depends_on:
      - kingshard
      - laracom-nats
      - etcd1
      - etcd2
      - etcd3
    build: ./user-service
    ports:
      - 9092:9091
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "laracom-nats:4222"
      DB_HOST: "kingshard:9696"
      DB_NAME: "laracom_user"
      DB_USER: "kingshard"
      DB_PASSWORD: "kingshard"

  laracom-user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"

  laracom-nats:
    image: nats:latest
    ports:
      - 4222:4222
    restart: always

  laracom-product-service:
    depends_on:
      - laracom-product-db
      - etcd1
      - etcd2
      - etcd3
    build: ./product-service
    ports:
      - 9093:9091
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
      DB_HOST: "laracom-product-db:3306"
      DB_NAME: "laracom_product"
      DB_USER: "product"
      DB_PASSWORD: "test"

  laracom-product-db:
    image: mysql:5.7
    ports:
      - 33062:3306
    volumes:
      - db_product_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: "product"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "laracom_product"
      MYSQL_ROOT_PASSWORD: "root"

  laracom-micro-api:
    image: socylx/micro:latest
    environment:
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
    ports:
      - 8888:8080
    command: api --handler=rpc --namespace=laracom.service

  laracom-web-dashboard:
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    image: xpunch/go-micro-dashboard:latest
    container_name: laracom-web-dashboard
    ports:
      - "8082:8082"
    links:
      - laracom-user-service
    environment:
      - MICRO_REGISTRY=etcd
      - MICRO_REGISTRY_ADDRESS=etcd1:2379,etcd2:2379,etcd3:2379
      - SERVER_ADDRESS=:8082
      - SERVER_AUTH_USERNAME=admin
      - SERVER_AUTH_PASSWORD=micro

  etcd1:
    image: bitnami/etcd:latest
    container_name: etcd1
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_NAME: "etcd1"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd1:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd1:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
    ports:
      - 23791:2379
      - 23801:2380

  etcd2:
    image: bitnami/etcd:latest
    container_name: etcd2
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_NAME: "etcd2"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd2:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd2:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
    ports:
      - 23792:2379
      - 23802:2380

  etcd3:
    image: bitnami/etcd:latest
    container_name: etcd3
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_NAME: "etcd3"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd3:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd3:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
    ports:
      - 23793:2379
      - 23803:2380

  e3w:
    image: soyking/e3w:latest
    ports:
      - "8088:8080"
    volumes:
      - ./conf/e3w/config.ini:/app/conf/config.default.ini

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./conf/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    restart: always

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9993:9093
    volumes:
      - ./conf/alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8083:8080
    restart: always
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./conf/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./conf/grafana/config.monitoring
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  user-db-master:
    env_file:
      - mysql-cluster/user/db.env
    image: mysql/mysql-server:5.7
    volumes:
      - userdb_data_1:/var/lib/mysql
    ports:
      - "3301:3306"
    command: [ "mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin=replicas-mysql-bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password" ]
    depends_on:
      - user-db-slave-1
      - user-db-slave-2

  user-db-slave-1:
    env_file:
      - mysql-cluster/user/db.env
    image: mysql/mysql-server:5.7
    volumes:
      - userdb_data_2:/var/lib/mysql
    ports:
      - "3302:3306"
    command: [ "mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password" ]

  user-db-slave-2:
    env_file:
      - mysql-cluster/user/db.env
    image: mysql/mysql-server:5.7
    volumes:
      - userdb_data_3:/var/lib/mysql
    ports:
      - "3303:3306"
    command: [ "mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password" ]

  kingshard:
    image: matjazmav/kingshard
    volumes:
      - ./mysql-cluster/user/ks.yaml:/etc/ks.yaml
    ports:
      - "9696:9696"
    expose:
      - "9696"
    depends_on:
      - user-db-master
    restart: always

volumes:
  db_user_data: { }
  db_product_data: { }
  grafana_data: { }
  prometheus_data: { }
  userdb_data_1: { }
  userdb_data_2: { }
  userdb_data_3: { }
