// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/demo/demo.proto

package demo

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for DemoService service

func NewDemoServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for DemoService service

type DemoService interface {
	SayHello(ctx context.Context, in *DemoRequest, opts ...client.CallOption) (*DemoResponse, error)
}

type demoService struct {
	c    client.Client
	name string
}

func NewDemoService(name string, c client.Client) DemoService {
	return &demoService{
		c:    c,
		name: name,
	}
}

func (c *demoService) SayHello(ctx context.Context, in *DemoRequest, opts ...client.CallOption) (*DemoResponse, error) {
	req := c.c.NewRequest(c.name, "DemoService.SayHello", in)
	out := new(DemoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DemoService service

type DemoServiceHandler interface {
	SayHello(context.Context, *DemoRequest, *DemoResponse) error
}

func RegisterDemoServiceHandler(s server.Server, hdlr DemoServiceHandler, opts ...server.HandlerOption) error {
	type demoService interface {
		SayHello(ctx context.Context, in *DemoRequest, out *DemoResponse) error
	}
	type DemoService struct {
		demoService
	}
	h := &demoServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DemoService{h}, opts...))
}

type demoServiceHandler struct {
	DemoServiceHandler
}

func (h *demoServiceHandler) SayHello(ctx context.Context, in *DemoRequest, out *DemoResponse) error {
	return h.DemoServiceHandler.SayHello(ctx, in, out)
}
